### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Kpaubert** [AndreasWintherMoen/yapp#2]
Software testing is the act of examining the artifacts and the behavior of the software under test by validation and verification. Software testing can also provide an objective, independent view of the software to allow the business to appreciate and understand the risks of software implementation.

**Comment by FredrikAugust** [comment]
Personally. I think a Test Driven Design (TDD) will benefit this project. What do you think @blauks?

**Comment by Kpaubert** [comment]
Protuding thought, @FredrikAugust !

**Comment by blauks** [comment]
I personally think that an incremental water flow model, with aspects from SCRUM and a hint of TOGAF would better suit this project.

**Comment by blauks** [comment]
Never been a fan of tests.

**Comment by erikskaar** [comment]
I agree with @blauks. Tests suck and I don't know how to write good tests so they are redundant.

**Comment by FredrikAugust** [comment]
> I personally think that an incremental water flow model, with aspects from SCRUM and a hint of TOGAF would better suit this project.

If we opt for this solution; where would the water flow?

**Comment by erikskaar** [comment]
> If we opt for this solution; where would the water flow?

My suggestion is either [sink.js](https://github.com/jussi-kalliokoski/sink.js/) or [drain.js](https://www.npmjs.com/package/drain-js). They might have nothing to do with water, but the name fits.

**Comment by Kpaubert** [comment]
Closing this due to wanting to.

**Comment by FredrikAugust** [comment]
Reckless!
